version: '3'
  
networks:
  superdupernet:

services:
  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./CERN_REALM.json:/tmp/testrealm.json
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/testrealm.json
    networks: 
      - superdupernet
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
  nginx:
    ports: 
      - 80:80
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks: 
      superdupernet:
        aliases: 
          - keycloak-127-0-0-1.nip.io
    depends_on: 
      - keycloak
  api:
    image: tomcat:jdk11-openjdk
    volumes: 
      - ./api/build/libs/api.war:/usr/local/tomcat/webapps/ROOT.war
    environment: 
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    ports:
      - 8000:8000
    depends_on: 
      - nginx
    networks: 
      - superdupernet
  ui:
    image: node:latest
    working_dir: /app
    volumes: 
      - ./ui:/app
    environment: 
      CI: "true"
    ports:
      - 3000:3000
    depends_on: 
      - api
    networks: 
      - superdupernet
    command: sh -c "npm install && npm start"